# Generated by Django 3.0 on 2020-07-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200724_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_data',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
