# Generated by Django 3.0 on 2020-07-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200724_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodCal', models.FloatField()),
                ('foodName', models.CharField(max_length=125)),
                ('trait', models.CharField(max_length=30)),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('carb', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='post_data',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
