# Generated by Django 3.0 on 2020-07-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200725_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_data',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post_data',
            name='dailyExtraConsume',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='post_data',
            name='dateOfJoin',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post_data',
            name='specialDiet',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
