# Generated by Django 3.0 on 2020-07-26 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200725_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeId', models.IntegerField()),
                ('foodName', models.CharField(max_length=125)),
                ('cal', models.FloatField()),
                ('foodId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.foodTable')),
            ],
        ),
    ]
