# Generated by Django 3.0 on 2020-07-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_recipetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipetable',
            name='cal',
        ),
        migrations.RemoveField(
            model_name='recipetable',
            name='foodId',
        ),
        migrations.RemoveField(
            model_name='recipetable',
            name='foodName',
        ),
        migrations.RemoveField(
            model_name='recipetable',
            name='recipeId',
        ),
        migrations.AddField(
            model_name='recipetable',
            name='cal1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipetable',
            name='cal2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipetable',
            name='cal3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipetable',
            name='foodItem1',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='recipetable',
            name='foodItem2',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='recipetable',
            name='foodItem3',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
