# Generated by Django 3.0 on 2020-07-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200725_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetable',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
