# Generated by Django 3.0 on 2020-07-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200725_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetable',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
