# Generated by Django 3.0 on 2020-07-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200726_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_data',
            name='dateOfJoin',
        ),
        migrations.AlterField(
            model_name='post_data',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
