# Generated by Django 3.0 on 2020-07-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200728_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_data',
            name='id',
            field=models.IntegerField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
