# Generated by Django 3.0 on 2020-07-30 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200728_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtable',
            name='restrict',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='recipetable',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.post_data'),
        ),
    ]
