# Generated by Django 3.0 on 2020-08-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200729_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipetable',
            name='cal4',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipetable',
            name='cal5',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipetable',
            name='foodItem4',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='recipetable',
            name='foodItem5',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
