# Generated by Django 3.0 on 2020-08-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200801_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetable',
            name='user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
