# Generated by Django 3.0 on 2020-08-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200801_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipetable',
            name='totalCal',
            field=models.FloatField(default=0),
        ),
    ]
