# Generated by Django 3.0 on 2020-08-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_recipetable_totalcal'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='foodtable',
            index=models.Index(fields=['foodCal'], name='main_foodta_foodCal_ae30ef_idx'),
        ),
        migrations.AddIndex(
            model_name='foodtable',
            index=models.Index(fields=['foodCal', 'trait', 'restrict'], name='main_foodta_foodCal_177eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='recipetable',
            index=models.Index(fields=['user'], name='main_recipe_user_d0123e_idx'),
        ),
    ]
